<?php 
defined('UNLOCK_IMPORT') || define('UNLOCK_IMPORT',TRUE);   
require_once __DIR__.'/../../include/customerOnlyResponse.php'; // Customer only Json response
require_once __DIR__.'/../../include/getCouponDetails.php'; // Get coupon details

// Note:
// This api call gets all coupons generated by the user

// Usage: 
// $_POST['token']: Token for authentication

// Result:
// $response['coupons']: The coupons obtained

$uid = getVerifiedUid();
$sql = getAllCouponsSQL();
$sql .= "WHERE `generatedCoupons`.`ownerUid` = ? ORDER BY `generatedCoupons`.`generatedDate` DESC";

if ($stmt = $mysqli->prepare($sql)) {
    $stmt->bind_param("i", $uid);
    $stmt->execute();
    $response['coupons'] = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
    $stmt->close();
    returnSuccessful($response);
} else {
    returnError("Internal Error: Unable to retrieve generated coupons");
} 

?>